capture label variable Age_$start_MY "Age at spell start"
capture label variable Dur_Spell "Duration (months) of spell at spell end date"
capture label variable End_MY "End date in month years"
capture label variable IntDate_MY "Interview date in month years - not necessarily correct for spell!"
capture label variable LFS "Status in current spell (${numberofstates} states, using classification ${statenames})"
capture label variable LFS_1 "Status in previous spell (${numberofstates} states, using classification ${statenames})"
capture label variable LFS2 "Transition (change in status)"
capture label variable LFS2_B "Transition (change in status) including `birth' into first status"
capture label variable pidp "Cross-wave person identifier"
capture label variable Spell "Spell"
capture label variable Start_MY "Start date in month years"
capture label variable Status "Economic activity"
capture label variable TransitionDate "Date of transition (=current spell start date)"
capture label variable Wave "Wave (= 18 + Wave for UKHLS)"
capture label variable Weight "Cross-sectional weight"

// LABELS APPLIED IN "Dynamics_Durations.do":
//label variable Dur_`i' "Duration (months) in state `i' over lifetime up to and including current spell"
//label variable DurAtStart_`i' "Duration (months) in state `i' over lifetime up to end of previous spell/start of current spell"

// LABELS APPLIED IN "Dynamics_Counts.do":
//label variable CountSpell`i' "Count of spells of `i' to date"
//label variable CountTransition`i' "Count of transitions `i' to date"

// LABELS APPLIED IN "Dynamics_Flows.do":
/*
foreach i in $LFS2levels{	
	capture label variable Flows_M_`i' "Unweighted sum (count) of the `i' gross flows, by month and flow"
	}
capture label variable Flow_M_EE "EE unweighted flow rate Flows_M_EE/(Flows_M_EE+Flows_M_EN+Flows_M_EU+Flows_M_EM)"
capture label variable Flow_M_EN "EN unweighted flow rate Flows_M_EN/(Flows_M_EE+Flows_M_EN+Flows_M_EU+Flows_M_EM)"
capture label variable Flow_M_EU "EU unweighted flow rate Flows_M_EU/(Flows_M_EE+Flows_M_EN+Flows_M_EU+Flows_M_EM)"
capture label variable Flow_M_EM "EM unweighted flow rate Flows_M_EM/(Flows_M_EE+Flows_M_EN+Flows_M_EU+Flows_M_EM)"
capture label variable Flow_M_UE "UE unweighted flow rate Flows_M_UE/(Flows_M_UE+Flows_M_UN+Flows_M_UU+Flows_M_UM)"
capture label variable Flow_M_UN "UN unweighted flow rate Flows_M_UN/(Flows_M_UE+Flows_M_UN+Flows_M_UU+Flows_M_UM)"
capture label variable Flow_M_UU "UU unweighted flow rate Flows_M_UU/(Flows_M_UE+Flows_M_UN+Flows_M_UU+Flows_M_UM)"
capture label variable Flow_M_UM "UM unweighted flow rate Flows_M_UM/(Flows_M_UE+Flows_M_UN+Flows_M_UU+Flows_M_UM)"
capture label variable Flow_M_NE "NE unweighted flow rate Flows_M_NE/(Flows_M_NE+Flows_M_NN+Flows_M_NU+Flows_M_NM)"
capture label variable Flow_M_NN "NN unweighted flow rate Flows_M_NN/(Flows_M_NE+Flows_M_NN+Flows_M_NU+Flows_M_NM)"
capture label variable Flow_M_NU "NU unweighted flow rate Flows_M_NU/(Flows_M_NE+Flows_M_NN+Flows_M_NU+Flows_M_NM)"
capture label variable Flow_M_NM "NM unweighted flow rate Flows_M_NM/(Flows_M_NE+Flows_M_NN+Flows_M_NU+Flows_M_NM)"
capture label variable Flow_Q_EE "EE unweighted flow rate Flows_Q_EE/(Flows_Q_EE+Flows_Q_EN+Flows_Q_EU+Flows_Q_EM)"
capture label variable Flow_Q_EN "EN unweighted flow rate Flows_Q_EN/(Flows_Q_EE+Flows_Q_EN+Flows_Q_EU+Flows_Q_EM)"
capture label variable Flow_Q_EU "EU unweighted flow rate Flows_Q_EU/(Flows_Q_EE+Flows_Q_EN+Flows_Q_EU+Flows_Q_EM)"
capture label variable Flow_Q_EM "EM unweighted flow rate Flows_Q_EM/(Flows_Q_EE+Flows_Q_EN+Flows_Q_EU+Flows_Q_EM)"
capture label variable Flow_Q_UE "UE unweighted flow rate Flows_Q_UE/(Flows_Q_UE+Flows_Q_UN+Flows_Q_UU+Flows_Q_UM)"
capture label variable Flow_Q_UN "UN unweighted flow rate Flows_Q_UN/(Flows_Q_UE+Flows_Q_UN+Flows_Q_UU+Flows_Q_UM)"
capture label variable Flow_Q_UU "UU unweighted flow rate Flows_Q_UU/(Flows_Q_UE+Flows_Q_UN+Flows_Q_UU+Flows_Q_UM)"
capture label variable Flow_Q_UM "UM unweighted flow rate Flows_Q_UM/(Flows_Q_UE+Flows_Q_UN+Flows_Q_UU+Flows_Q_UM)"
capture label variable Flow_Q_NE "NE unweighted flow rate Flows_Q_NE/(Flows_Q_NE+Flows_Q_NN+Flows_Q_NU+Flows_Q_NM)"
capture label variable Flow_Q_NN "NN unweighted flow rate Flows_Q_NN/(Flows_Q_NE+Flows_Q_NN+Flows_Q_NU+Flows_Q_NM)"
capture label variable Flow_Q_NU "NU unweighted flow rate Flows_Q_NU/(Flows_Q_NE+Flows_Q_NN+Flows_Q_NU+Flows_Q_NM)"
capture label variable Flow_Q_NM "NM unweighted flow rate Flows_Q_NM/(Flows_Q_NE+Flows_Q_NN+Flows_Q_NU+Flows_Q_NM)"		
capture label variable Flow_Y_EE "EE unweighted flow rate Flows_Y_EE/(Flows_Y_EE+Flows_Y_EN+Flows_Y_EU+Flows_Y_EM)"
capture label variable Flow_Y_EN "EN unweighted flow rate Flows_Y_EN/(Flows_Y_EE+Flows_Y_EN+Flows_Y_EU+Flows_Y_EM)"
capture label variable Flow_Y_EU "EU unweighted flow rate Flows_Y_EU/(Flows_Y_EE+Flows_Y_EN+Flows_Y_EU+Flows_Y_EM)"
capture label variable Flow_Y_EM "EM unweighted flow rate Flows_Y_EM/(Flows_Y_EE+Flows_Y_EN+Flows_Y_EU+Flows_Y_EM)"
capture label variable Flow_Y_UE "UE unweighted flow rate Flows_Y_UE/(Flows_Y_UE+Flows_Y_UN+Flows_Y_UU+Flows_Y_UM)"
capture label variable Flow_Y_UN "UN unweighted flow rate Flows_Y_UN/(Flows_Y_UE+Flows_Y_UN+Flows_Y_UU+Flows_Y_UM)"
capture label variable Flow_Y_UU "UU unweighted flow rate Flows_Y_UU/(Flows_Y_UE+Flows_Y_UN+Flows_Y_UU+Flows_Y_UM)"
capture label variable Flow_Y_UM "UM unweighted flow rate Flows_Y_UM/(Flows_Y_UE+Flows_Y_UN+Flows_Y_UU+Flows_Y_UM)"
capture label variable Flow_Y_NE "NE unweighted flow rate Flows_Y_NE/(Flows_Y_NE+Flows_Y_NN+Flows_Y_NU+Flows_Y_NM)"
capture label variable Flow_Y_NN "NN unweighted flow rate Flows_Y_NN/(Flows_Y_NE+Flows_Y_NN+Flows_Y_NU+Flows_Y_NM)"
capture label variable Flow_Y_NU "NU unweighted flow rate Flows_Y_NU/(Flows_Y_NE+Flows_Y_NN+Flows_Y_NU+Flows_Y_NM)"
capture label variable Flow_Y_NM "NM unweighted flow rate Flows_Y_NM/(Flows_Y_NE+Flows_Y_NN+Flows_Y_NU+Flows_Y_NM)"	
foreach i in $LFS2levels{	
	capture label variable Flows_M_W_`i' "Weighted sum of the `i' gross flows, by month and flow"
	}
capture label variable Flow_M_W_EE "EE weighted flow rate Flows_M_W_EE/(Flows_M_W_EE+Flows_M_W_EN+Flows_M_W_EU+Flows_M_W_EM)"
capture label variable Flow_M_W_EN "EN weighted flow rate Flows_M_W_EN/(Flows_M_W_EE+Flows_M_W_EN+Flows_M_W_EU+Flows_M_W_EM)"
capture label variable Flow_M_W_EU "EU weighted flow rate Flows_M_W_EU/(Flows_M_W_EE+Flows_M_W_EN+Flows_M_W_EU+Flows_M_W_EM)"
capture label variable Flow_M_W_EM "EM weighted flow rate Flows_M_W_EM/(Flows_M_W_EE+Flows_M_W_EN+Flows_M_W_EU+Flows_M_W_EM)"
capture label variable Flow_M_W_UE "UE weighted flow rate Flows_M_W_UE/(Flows_M_W_UE+Flows_M_W_UN+Flows_M_W_UU+Flows_M_W_UM)"
capture label variable Flow_M_W_UN "UN weighted flow rate Flows_M_W_UN/(Flows_M_W_UE+Flows_M_W_UN+Flows_M_W_UU+Flows_M_W_UM)"
capture label variable Flow_M_W_UU "UU weighted flow rate Flows_M_W_UU/(Flows_M_W_UE+Flows_M_W_UN+Flows_M_W_UU+Flows_M_W_UM)"
capture label variable Flow_M_W_UM "UM weighted flow rate Flows_M_W_UM/(Flows_M_W_UE+Flows_M_W_UN+Flows_M_W_UU+Flows_M_W_UM)"
capture label variable Flow_M_W_NE "NE weighted flow rate Flows_M_W_NE/(Flows_M_W_NE+Flows_M_W_NN+Flows_M_W_NU+Flows_M_W_NM)"
capture label variable Flow_M_W_NN "NN weighted flow rate Flows_M_W_NN/(Flows_M_W_NE+Flows_M_W_NN+Flows_M_W_NU+Flows_M_W_NM)"
capture label variable Flow_M_W_NU "NU weighted flow rate Flows_M_W_NU/(Flows_M_W_NE+Flows_M_W_NN+Flows_M_W_NU+Flows_M_W_NM)"
capture label variable Flow_M_W_NM "NM weighted flow rate Flows_M_W_NM/(Flows_M_W_NE+Flows_M_W_NN+Flows_M_W_NU+Flows_M_W_NM)"
capture label variable Flow_Q_W_EE "EE weighted flow rate Flows_Q_W_EE/(Flows_Q_W_EE+Flows_Q_W_EN+Flows_Q_W_EU+Flows_Q_W_EM)"
capture label variable Flow_Q_W_EN "EN weighted flow rate Flows_Q_W_EN/(Flows_Q_W_EE+Flows_Q_W_EN+Flows_Q_W_EU+Flows_Q_W_EM)"
capture label variable Flow_Q_W_EU "EU weighted flow rate Flows_Q_W_EU/(Flows_Q_W_EE+Flows_Q_W_EN+Flows_Q_W_EU+Flows_Q_W_EM)"
capture label variable Flow_Q_W_EM "EM weighted flow rate Flows_Q_W_EM/(Flows_Q_W_EE+Flows_Q_W_EN+Flows_Q_W_EU+Flows_Q_W_EM)"
capture label variable Flow_Q_W_UE "UE weighted flow rate Flows_Q_W_UE/(Flows_Q_W_UE+Flows_Q_W_UN+Flows_Q_W_UU+Flows_Q_W_UM)"
capture label variable Flow_Q_W_UN "UN weighted flow rate Flows_Q_W_UN/(Flows_Q_W_UE+Flows_Q_W_UN+Flows_Q_W_UU+Flows_Q_W_UM)"
capture label variable Flow_Q_W_UU "UU weighted flow rate Flows_Q_W_UU/(Flows_Q_W_UE+Flows_Q_W_UN+Flows_Q_W_UU+Flows_Q_W_UM)"
capture label variable Flow_Q_W_UM "UM weighted flow rate Flows_Q_W_UM/(Flows_Q_W_UE+Flows_Q_W_UN+Flows_Q_W_UU+Flows_Q_W_UM)"
capture label variable Flow_Q_W_NE "NE weighted flow rate Flows_Q_W_NE/(Flows_Q_W_NE+Flows_Q_W_NN+Flows_Q_W_NU+Flows_Q_W_NM)"
capture label variable Flow_Q_W_NN "NN weighted flow rate Flows_Q_W_NN/(Flows_Q_W_NE+Flows_Q_W_NN+Flows_Q_W_NU+Flows_Q_W_NM)"
capture label variable Flow_Q_W_NU "NU weighted flow rate Flows_Q_W_NU/(Flows_Q_W_NE+Flows_Q_W_NN+Flows_Q_W_NU+Flows_Q_W_NM)"
capture label variable Flow_Q_W_NM "NM weighted flow rate Flows_Q_W_NM/(Flows_Q_W_NE+Flows_Q_W_NN+Flows_Q_W_NU+Flows_Q_W_NM)"		
capture label variable Flow_Y_W_EE "EE weighted flow rate Flows_Y_W_EE/(Flows_Y_W_EE+Flows_Y_W_EN+Flows_Y_W_EU+Flows_Y_W_EM)"
capture label variable Flow_Y_W_EN "EN weighted flow rate Flows_Y_W_EN/(Flows_Y_W_EE+Flows_Y_W_EN+Flows_Y_W_EU+Flows_Y_W_EM)"
capture label variable Flow_Y_W_EU "EU weighted flow rate Flows_Y_W_EU/(Flows_Y_W_EE+Flows_Y_W_EN+Flows_Y_W_EU+Flows_Y_W_EM)"
capture label variable Flow_Y_W_EM "EM weighted flow rate Flows_Y_W_EM/(Flows_Y_W_EE+Flows_Y_W_EN+Flows_Y_W_EU+Flows_Y_W_EM)"
capture label variable Flow_Y_W_UE "UE weighted flow rate Flows_Y_W_UE/(Flows_Y_W_UE+Flows_Y_W_UN+Flows_Y_W_UU+Flows_Y_W_UM)"
capture label variable Flow_Y_W_UN "UN weighted flow rate Flows_Y_W_UN/(Flows_Y_W_UE+Flows_Y_W_UN+Flows_Y_W_UU+Flows_Y_W_UM)"
capture label variable Flow_Y_W_UU "UU weighted flow rate Flows_Y_W_UU/(Flows_Y_W_UE+Flows_Y_W_UN+Flows_Y_W_UU+Flows_Y_W_UM)"
capture label variable Flow_Y_W_UM "UM weighted flow rate Flows_Y_W_UM/(Flows_Y_W_UE+Flows_Y_W_UN+Flows_Y_W_UU+Flows_Y_W_UM)"
capture label variable Flow_Y_W_NE "NE weighted flow rate Flows_Y_W_NE/(Flows_Y_W_NE+Flows_Y_W_NN+Flows_Y_W_NU+Flows_Y_W_NM)"
capture label variable Flow_Y_W_NN "NN weighted flow rate Flows_Y_W_NN/(Flows_Y_W_NE+Flows_Y_W_NN+Flows_Y_W_NU+Flows_Y_W_NM)"
capture label variable Flow_Y_W_NU "NU weighted flow rate Flows_Y_W_NU/(Flows_Y_W_NE+Flows_Y_W_NN+Flows_Y_W_NU+Flows_Y_W_NM)"
capture label variable Flow_Y_W_NM "NM weighted flow rate Flows_Y_W_NM/(Flows_Y_W_NE+Flows_Y_W_NN+Flows_Y_W_NU+Flows_Y_W_NM)"		
*/

capture label values Status status
